import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { DSH_DEFAULT_MODEL, type DshModelSmokeTestResult } from '../shared/agent-backend-contract.js'
import type { SearchPort } from '../shared/search-contract.js'
import { AgentRunError, AgentRunner, type AgentRunnerPort } from '../shared/agent-runtime.js'
import { buildDshDeepRadarIntentPrompt, buildDshIntentPrompt, buildDshOpportunityPrompt, createControllerDshTaskExecutor, DshAgentBackend, runDshModelSmokeTest, type DshPromptBuilder, type DshTaskExecutor, type OpportunityDiscoveryPort } from './dsh-agent-backend.js'
import { inspectDshCapabilityPackage, type DshCapabilityLock } from './dsh-capability-package.js'
import { DSH_RELEASE_LOCK } from './dsh-release-lock.js'
import { DshRuntimeController } from './dsh-runtime-controller.js'
import { createDshDeepSeekSearchPort, loadInstalledDshDeepSeekSearchProvider } from './dsh-search-provider.js'
import { loadOfficialDshClientFactory } from './dsh-sdk-client.js'
import type { NearbyOpportunityLocator } from './nearby-opportunity-locator.js'
import { buildAgentLoopStepPrompt, buildEvidenceSynthesisPrompt, serializeSynthesisPayload, type EvidenceSynthesisPayload, type LoopStepPayload } from './evidence-synthesis-backend.js'
import { buildLeadPlanPrompt, type LeadPlanPayload } from './lead-plan-prompt.js'
import type { AgentTask } from '../shared/agent-contract.js'

export type InstalledDshBackendPreparation =
  | {
      available: true
      runner: AgentRunnerPort
      testModel: () => Promise<DshModelSmokeTestResult>
      searchPort: SearchPort
      /** 归纳通道：把证据表交给模型，拿回结构化归纳（经本地引文校验后才可用）。 */
      synthesize: (payload: EvidenceSynthesisPayload) => Promise<string>
      /** Agent Loop：一次调用跑一轮，返回动作 JSON。 */
      runLoopStep: (payload: LoopStepPayload) => Promise<string>
  planLeadSearch: (payload: LeadPlanPayload) => Promise<string>
    }
  | { available: false; reason: string }

export const DSH_MODEL_ONLY_CORDIS_CONFIG = `# Generated by Shiji. Model-only phase: no shell, jobs, skills, or workspace context.
- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'

- id: agent-core
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    workspaceContext: false
    includeRuntimeContext: false
    skills:
      enabled: false
    toolBash: false
    toolJobs: false
    goals: false

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    thinking: disabled
    reasoningEffort: off

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'

`

export interface InstalledDshBackendOptions {
  packageRoot: string
  /** Packaged Windows releases may ship an architecture-pruned, separately locked runtime tree. */
  releaseLock?: DshCapabilityLock
  electronExecutable: string
  workspaceRoot: string
  sessionRoot: string
  readDeepSeekKey: () => Promise<string | undefined>
  /** 用户的豆包搜索 Key（与 DeepSeek 模型 Key 相互独立；缺失不阻塞启动）。 */
  readDoubaoKey?: () => Promise<string | undefined>
  discoverOpportunity: OpportunityDiscoveryPort
  locateNearbyOpportunity?: NearbyOpportunityLocator
}

export async function prepareInstalledDshBackend(
  options: InstalledDshBackendOptions,
): Promise<InstalledDshBackendPreparation> {
  const inspection = await inspectDshCapabilityPackage(options.packageRoot, options.releaseLock ?? DSH_RELEASE_LOCK)
  if (!inspection.available) return { available: false, reason: inspection.message }

  let createClient
  try {
    createClient = await loadOfficialDshClientFactory(inspection.package.sdkClient)
  } catch {
    return { available: false, reason: 'DSH 官方 SDK Client 无法加载。' }
  }

  // provider 放在会话目录（能力包外）：能力包有 manifest 完整性校验，不能往里写文件。
  // 因此该插件必须零依赖（不使用 @deepseek-ai/* 导入），只用 ctx.web。
  let doubaoProviderPath: string | undefined
  try {
    const source = await readFile(path.join(import.meta.dirname, 'dsh-plugin-doubao-web.js'), 'utf8')
    doubaoProviderPath = path.join(options.sessionRoot, 'shiji-doubao-web.mjs')
    await writeFile(doubaoProviderPath, source, 'utf8')
  } catch {
    doubaoProviderPath = undefined
  }
  const doubaoKey = await options.readDoubaoKey?.().catch(() => undefined)
  const modelOnlyConfig = path.join(options.sessionRoot, 'runtime.model-only.cordis.yml')
  try {
    await mkdir(options.sessionRoot, { recursive: true })
    await writeFile(modelOnlyConfig, DSH_MODEL_ONLY_CORDIS_CONFIG, 'utf8')
  } catch {
    return { available: false, reason: '无法准备 DSH 精简运行配置。' }
  }

  const createController = (apiKey: string) => {
    const environment = {
      ...process.env,
      ELECTRON_RUN_AS_NODE: '1',
      DSH_CORDIS_CONFIG: modelOnlyConfig,
      DSH_CWD: options.workspaceRoot,
      DSH_SESSION_ROOT: options.sessionRoot,
      ...(doubaoProviderPath ? { DSH_DOUBAO_PROVIDER_PATH: doubaoProviderPath } : {}),
      ...(doubaoKey ? { SHIJI_DOUBAO_SEARCH_KEY: doubaoKey } : {}),
    }
    return new DshRuntimeController({
      launch: { command: options.electronExecutable, args: [inspection.package.runtimeEntry], cwd: options.workspaceRoot },
      dshVersionProbe: {
        command: options.electronExecutable,
        args: ['-e', `process.stdout.write(${JSON.stringify(DSH_RELEASE_LOCK.dshVersion)})`],
      },
      nodeVersionProbe: { command: options.electronExecutable, args: ['-p', 'process.versions.node'] },
      expectedVersions: { dsh: DSH_RELEASE_LOCK.dshVersion, node: DSH_RELEASE_LOCK.nodeVersion },
      expectedIdentity: DSH_RELEASE_LOCK.runtimeIdentity,
      createClient,
      environment,
      runtimeSecrets: { deepseekApiKey: apiKey },
    })
  }

  const createExecutor = async (promptBuilder: DshPromptBuilder): Promise<DshTaskExecutor> => {
    const apiKey = await options.readDeepSeekKey()
    if (!apiKey) throw new AgentRunError('RUNTIME_ERROR', '请先在设置中保存 DeepSeek API Key。')
    const controller = createController(apiKey)
    return createControllerDshTaskExecutor(controller, {
      cwd: options.workspaceRoot,
      provider: 'deepseek-official',
      model: DSH_DEFAULT_MODEL,
    }, promptBuilder)
  }

  const backend = new DshAgentBackend(async (task, context, discovery) => {
    const execute = await createExecutor(buildDshOpportunityPrompt)
    return execute(task, context, discovery)
  }, options.discoverOpportunity, options.locateNearbyOpportunity, async (task, context) => {
    const execute = await createExecutor(task.kind === 'deep-radar-search' ? buildDshDeepRadarIntentPrompt : buildDshIntentPrompt)
    return execute({ ...task, id: `${task.id}-intent` }, context)
  })
  const testModel = async () => {
    const apiKey = await options.readDeepSeekKey()
    if (!apiKey) throw new AgentRunError('RUNTIME_ERROR', '请先在设置中保存 DeepSeek API Key。')
    return runDshModelSmokeTest(createController(apiKey), {
      cwd: options.workspaceRoot,
      provider: 'deepseek-official',
      model: DSH_DEFAULT_MODEL,
    })
  }
  const searchPort = createDshDeepSeekSearchPort(
    () => loadInstalledDshDeepSeekSearchProvider(inspection.package.root),
    options.readDeepSeekKey,
  )
  // 归纳通道（2026-09-16 新增）：复用同一个 DSH 会话执行器，只换提示词构造器；
  // 现有三种搜索任务与雷达意图执行器保持原样，不受影响。
  const synthesize = async (payload: EvidenceSynthesisPayload): Promise<string> => {
    const execute = await createExecutor(buildEvidenceSynthesisPrompt)
    const task = {
      id: `synthesis-${Date.now()}`,
      kind: 'opportunity-search',
      criteria: {},
      inputMode: 'free',
      searchQuery: serializeSynthesisPayload(payload),
    } as unknown as AgentTask
    const controller = new AbortController()
    const result = await execute(task, { signal: controller.signal, onNotification: () => {} })
    return result.finalResponse ?? ''
  }
  // Agent Loop 通道：一次调用只跑一轮，返回模型的动作 JSON（search / submit）。
  const runLoopStep = async (payload: LoopStepPayload): Promise<string> => {
    const execute = await createExecutor(buildAgentLoopStepPrompt)
    const task = {
      id: `loop-${Date.now()}`,
      kind: 'opportunity-search',
      criteria: {},
      inputMode: 'free',
      searchQuery: JSON.stringify(payload),
    } as unknown as AgentTask
    const result = await execute(task, { signal: new AbortController().signal, onNotification: () => {} })
    return result.finalResponse ?? ''
  }
  // 获客补充轮通道：复用同一个会话执行器，只换提示词构造器（只回一条查询）。
  const planLeadSearch = async (payload: LeadPlanPayload): Promise<string> => {
    const execute = await createExecutor(buildLeadPlanPrompt)
    const task = {
      id: `lead-plan-${Date.now()}`,
      kind: 'opportunity-search',
      criteria: {},
      inputMode: 'free',
      searchQuery: JSON.stringify(payload),
    } as unknown as AgentTask
    const result = await execute(task, { signal: new AbortController().signal, onNotification: () => {} })
    return result.finalResponse ?? ''
  }
  return { available: true, runner: new AgentRunner(backend), testModel, searchPort, synthesize, runLoopStep, planLeadSearch }
}

export function installedDshPackageRoot(userDataRoot: string): string {
  return path.join(userDataRoot, 'capabilities', 'dsh', DSH_RELEASE_LOCK.dshVersion)
}
